# Generated by Django 4.2.6 on 2023-10-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='addtask',
            name='pending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
